feat($uibModal): bind resolve properties to controller when opening modal as component
angular-ui/bootstrap pull request #6569
Opened 2017-06-09 19:53 UTC by austinleroy

Bind resolve properties to controller of component opened with $uibModal.
This mimics current uiRouter usage of resolve so any component can receive
input data with $uibModal.  Previous behavior was to force component to
expose a resolve binding.

Closes #6540

2017-06-17 05:22 UTC, eseliger commented
Would love to see that merged, so we can reuse our modal components anywhere else in applications

2017-06-27 15:23 UTC, AnimaLupi commented
Indeed, it's a much needed merge to ensure reusability...

2017-06-30 19:44 UTC, austinleroy commented
I'd like to note that this PR is usable **only for binding data to the component**.  Binding of callback functions is still not available.  If that were ever to be supported, I believe it would not be a part of `resolve`.

That being said, this would still improve the reusability of any component opened with $uibModal.

2017-07-18 06:39 UTC, bitflower commented
In which version will this be included? I could patch but it's a big project with many devs on board...

2017-08-08 10:32 UTC, bitflower requested changes
Hey, I ran into issues with bindings that have the camelCase and need to convert to dash-case.

See my comment.

2017-08-08 10:32 UTC, bitflower commented on src/modal/modal.js
> +              content.attr(property, '$resolve.' + property);
It should be something like
`content.attr(property.replace(/[A-Z]/g, function(c) { return '-' + c.toLowerCase(); }), '$resolve.' + property);`
to make it respect the angular "snake case" / dash-case for bindings with caps in their name (eg. mySuperDuperBinding -> my-super-duper-binding)

2017-08-08 10:33 UTC, bitflower commented on src/modal/modal.js
> +              content.attr(property, '$resolve.' + property);
Even better would be to call the angular-internal function for this conversion like angular.snakeCase() pseudo code....

2017-08-08 10:34 UTC, bitflower commented on src/modal/modal.js
> +              content.attr(property, '$resolve.' + property);
See code here: [https://github.com/angular/angular.js/blob/master/src/Angular.js#L1886](https://github.com/angular/angular.js/blob/master/src/Angular.js#L1886)

2017-08-09 19:40 UTC, austinleroy commented on src/modal/modal.js
> +              content.attr(property, '$resolve.' + property);
Great suggestion! I'll push up changes that should address that scenario.

2017-08-10 06:17 UTC, bitflower commented
@austinleroy  Do you understand the problem here? Would love to see this merged ;-)

2017-08-11 22:37 UTC, austinleroy commented
@bitflower It looks like the Travis build failed due to a timeout when running the karma task.  The build should work correctly if another one is kicked off - I can't do it myself because I don't have write access to this repo

2017-08-15 18:37 UTC, austinleroy commented
I read that if I close the PR and reopen it, a new Travis build will kick off...

2017-08-15 19:06 UTC, eseliger commented
For the future: you can also amend your commit and force push it

2022-03-14 15:23 UTC, closed without merging